languages:
   Ruby: true
engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Rails/Output:
        enabled: false
ratings:
   paths:
   - lib/**
exclude_paths:
- spec/**/*
- vendor/**/*
- tmp/**/*
- target/**/*
