before_install:
  - export JRUBY_OPTS="-Xcli.debug=true --debug"
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-20mode
  - jruby-21mode

script: bundle exec rspec
sudo: false
