before_install:
  - export JRUBY_OPTS="-Xcli.debug=true --debug"
language: ruby
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby-20mode
  - jruby-21mode
  - jruby-9.0.5.0

script: bundle exec rake
sudo: false

addons:
  code_climate:
    repo_token: 3377046eefe5079936ac6dd66241c7fac6e56c632a34b653ef7896e31fa048c1

cache:
  directories:
    - .spec-tmp
