local_repo '~/.m2/repository'
repository 'http://mirrors.ibiblio.org/pub/mirrors/maven2'

jar "org.apache.mina:mina-core:2.0.4"
local "spec/fixtures/naether-0.13.0.jar"
pom 'spec/pom.xml'

group 'development' do
    jar 'com.typesafe:config:jar:0.5.0'
end

group 'test' do
    jar 'org.testng:testng:jar:6.9.10'
end
