source 'https://rubygems.org'

# Specify your gem's dependencies in lock_jar_bundler.gemspec
gemspec

group :development do
  gem 'guard-rspec', :require => false
  gem 'pry'
  gem 'yard'
  gem 'jruby-openssl',   :platforms => :jruby
  gem 'rspec', '~>3.0.0'
  gem 'lock_jar', path: '../core'
end

# Test gems used in the specs when scanning for bundled jarfiles
group :test do
  gem 'dummy_gem', path: 'spec/dummy_gem'
end



