local '~/.m2/repository'
repository 'http://mirrors.ibiblio.org/pub/mirrors/maven2'

jar "org.apache.mina:mina-core:2.0.4"
pom 'spec/pom.xml'
    
scope 'runtime' do
    jar 'org.apache.tomcat:servlet-api:jar:6.0.35'
end

scope 'test' do
    jar 'junit:junit:jar:4.10'
end